export const helpCopy = {
  live: "This feature uses current production data and is available now.",
  advisory: "MIHARI recommends a review, but does not execute an action.",
  next: "This capability is planned and is not active yet.",
  watchScope: "The Stock Tokens selected for ongoing corporate-action monitoring.",
  dataMode: "Live uses Robinhood data. Simulated fallback is clearly labelled and never treated as personal evidence.",
  lastSync: "The last time MIHARI received a response from the current data source.",
  sourceStatus: "The lifecycle state reported by Robinhood, such as Pending, In progress or Completed.",
  risk: "Operational urgency based on the event and its possible downstream impact. It is not a price forecast.",
  confidence: "How complete and consistent the evidence is. It is not the probability of a loss.",
  affectedSystems: "Systems that may need review, such as quotes, NAV, vaults, lending or agents. This does not prove you use all of them.",
  chainProof: "An onchain receipt for an approved action. Not recorded means no transaction was executed.",
  monitoredAssets: "Assets in your saved watchlist. MIHARI checks them for official corporate actions.",
  verifiedWallets: "Wallets whose ownership was confirmed with a free message signature. MIHARI cannot move their funds.",
  stockTokenPositions: "Official Robinhood Stock Token balances found directly in verified wallets.",
  activeExposure: "A direct holding with a matching current corporate-action record.",
  observerAccess: "A registered profile with direct wallet scans, watchlist monitoring and standard limits.",
  holderAccess: "Unlocked when verified wallets hold the required $MHR balance. It adds higher limits and personal DeFi scans.",
  indicativeValue: "An estimate based on the latest available token balance and price. It is not an execution quote.",
  eventMatch: "An official corporate action matches the Stock Token identity in a holding, watchlist or supported protocol position.",
  noEventMatch: "No matching corporate-action record appears in the current source window. Monitoring continues.",
  activeSignals: "Current official events that match a holding, watchlist asset or supported protocol position.",
  trackedAssets: "Unique Stock Tokens included from holdings, watchlist assets and supported protocol positions.",
  directPaths: "Verified wallet holdings reached by a current official event.",
  protocolPaths: "Supported DeFi positions reached by a current official event. Holder access is required for personal scans.",
  provenExposure: "A balance or protocol position returned by a verified onchain source, not an assumption from the watchlist.",
  marketCoverage: "A supported market where the asset may trade. It does not mean your wallet owns a position there.",
  protocolPosition: "A recognized lending, vault, liquidity or perpetual position tied to a verified wallet.",
  partialSource: "Some data sources responded and others did not. MIHARI shows only what it could verify.",
  policyRecommendation: "A structured review plan created from a verified event. It never executes automatically.",
  priority: "How quickly an operator should review the recommendation. It is separate from the event source status.",
  applyWhen: "Conditions that make the recommendation relevant.",
  clearWhen: "Conditions that must be confirmed before the recommendation can be closed.",
  aiAnalysis: "AI explains verified source data. It does not invent events, approve transactions or control funds.",
  ruleBased: "A deterministic MIHARI fallback used when a new AI response is unavailable or unnecessary.",
} as const;
